//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioCraft.Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInquiry
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Budget { get; set; }
        public string Message { get; set; }
        public string Regarding { get; set; }
    }
}
